<?php
$root=dirname(__DIR__).'/pdf-library-foundation-12';
$read=static function(string $path)use($root):string{$full=$root.'/'.$path;if(!is_file($full)){fwrite(STDERR,"R23 missing target: {$path}\n");exit(1);}return (string)file_get_contents($full);};
$must=static function(string $haystack,string $needle,string $why):void{if(false===strpos($haystack,$needle)){fwrite(STDERR,"R23 regression: {$why}\n");exit(1);}};
$forbid=static function(string $haystack,string $needle,string $why):void{if(false!==strpos($haystack,$needle)){fwrite(STDERR,"R23 regression: {$why}\n");exit(1);}};
$core=$read('includes/class-pldr-core.php');$plugin=$read('includes/class-pldr-plugin.php');$schema=$read('includes/class-pldr-schema.php');$fschema=$read('includes/class-pldr-future-schema.php');$access=$read('includes/class-pldr-access.php');$ingest=$read('includes/class-pldr-ingest.php');$rights=$read('includes/class-pldr-rights.php');$rest=$read('includes/class-pldr-rest.php');$frest=$read('includes/class-pldr-future-rest.php');$future=$read('includes/class-pldr-future.php');$reader=$read('includes/class-pldr-reader.php');$main=$read('pdf-library-digital-reading.php');
$must($core,"if ('manage' === \$route) return home_url('/library/manage/');",'canonical /library/manage/ route URL missing');
$must($plugin,"add_rewrite_rule('^library/manage/?$'",'canonical /library/manage/ rewrite missing');
$must($plugin,"'manage'===\$route",'management route authorization/handoff missing');
$must($core,'public static function db_error_ref','opaque DB error reference helper missing');
$must($schema,"'last_error_ref'=>PLDR_Core::db_error_ref",'core schema still lacks safe DB diagnostic reference');
$must($fschema,"'last_error_ref'=>PLDR_Core::db_error_ref",'Future schema still lacks safe DB diagnostic reference');
$must($access,"Allow: GET, HEAD",'signed delivery method restriction missing');
$must($access,'requested_suffix < 1','zero-length suffix range guard missing');
$must($ingest,'cannot become an available derivative until the malware scanner produces a clean result','cover fail-closed scan gate missing');
$must($ingest,"'scan_status' => 'clean'",'verified cover scan state is not persisted as clean');
$must($rights,'pldr_restore_rights_expired','expired-rights restoration guard missing');
$must($rest,'idempotency_abort_after_transient_failed','core transient 5xx idempotency abort missing');
$must($frest,'future_idempotency_abort_after_transient_failed','Future transient 5xx idempotency abort missing');
$must($main,"login_enqueue_scripts', array('PLDR_Future', 'vault_purge_asset')",'logout/login-surface offline-vault purge missing');
$forbid($future,"add_action('wp_logout', array(__CLASS__, 'mark_vault_purge'))",'duplicate Future logout purge hook returned');
$must($reader,'suggested_limit=max(256,$target*4)','bounded catalog default scan budget missing');
$must($reader,'min(1000,$scan_limit)','catalog raw scan hard cap missing');
$must($main,'Version: 1.1.0-rc.','release-candidate version marker missing');
$must($main,"define('PLDR_VERSION', '1.1.0-rc.",'runtime release-candidate constant missing');
$must($main,"define('PLDR_DB_VERSION', '1.1.0')",'DB schema version drifted unexpectedly');
$doc=dirname(__DIR__).'/docs/TWENTY-ROUND-REVIEW-2026-08-13-R23.md';if(!is_file($doc)){fwrite(STDERR,"R23 review record missing.\n");exit(1);} $record=(string)file_get_contents($doc);for($i=1;$i<=20;$i++)$must($record,"## Round {$i}","R23 review record missing Round {$i}");
$must($record,'First-ten defect rounds: **1, 2, 3, 4, 6**','R23 first-ten defect summary missing');
$must($record,'Final defect rounds: **1, 2, 3, 4, 6, 13, 15, 19, 20**','R23 final defect summary missing');
echo "PLDR R23 fresh twenty-round corrective-review contract: PASS\n";
