<?php
$root=dirname(__DIR__).'/pdf-library-foundation-12';
$read=static function(string $path)use($root):string{$full=$root.'/'.$path;if(!is_file($full)){fwrite(STDERR,"R24 missing target: {$path}\n");exit(1);}return (string)file_get_contents($full);};
$must=static function(string $haystack,string $needle,string $why):void{if(false===strpos($haystack,$needle)){fwrite(STDERR,"R24 regression: {$why}\n");exit(1);}};
$forbid=static function(string $haystack,string $needle,string $why):void{if(false!==strpos($haystack,$needle)){fwrite(STDERR,"R24 regression: {$why}\n");exit(1);}};
$rights=$read('includes/class-pldr-rights.php');$ingest=$read('includes/class-pldr-ingest.php');$reader=$read('includes/class-pldr-reader.php');$frest=$read('includes/class-pldr-future-rest.php');$future=$read('includes/class-pldr-future.php');$vault=$read('assets/future-reader-vault.js');$css=$read('assets/reader.css')."\n".$read('assets/future-reader.css');$main=$read('pdf-library-digital-reading.php');
$must($rights,"array('route'=>'/library/manage/','owner'=>'12','visibility'=>'authenticated-noindex-no-cache')",'File 01 route registry is missing the governed /library/manage/ route');
$must($ingest,'pldr_rights_expired_ingest','already-expired rights can return to new-edition ingest');
$must($rights,'PLDR_Rights_Policy::check($document_id)','canonical publication/restore path no longer enforces rights policy');
$must($reader,'$next_ts<=$current_ts','reading-progress revision monotonicity guard missing');
$must($reader,'cursor_skip_remaining','access-filtered catalog cursor no longer carries outstanding logical skip');
$must($rights,'PLDR_R21_Outbox::dispatch();','legacy outbox entrypoint no longer delegates to the single governed R21 dispatcher');
$must($frest,"'/future/offline-authorization/(?P<edition>\\d+)'",'offline reconnect authorization endpoint missing');
$must($frest,"'callback'=>array(__CLASS__,'offline_authorization'),'permission_callback'=>array(__CLASS__,'logged_in')",'offline reconnect authorization is not authenticated');
$must($vault,'pldrOfflineReconnectReauth','offline vault reconnect reauthorization state missing');
$must($vault,'reauthorizeAfterReconnect','offline vault does not reauthorize after reconnect/before open');
$must($css,'#087A4E','Sabri Green fallback token missing');
$must($css,'--sabri-green','shared Sabri visual-token inheritance missing');
$forbid($css,'#166534','legacy competing primary green returned');
$forbid($css,'#15803d','legacy competing hover/primary green returned');
$must($future,'fingerprint_job_scheduled','edition-scoped fingerprint scheduler dedupe guard missing');
$must($future,"wp_next_scheduled('pldr_future_fingerprint_edition',array(\$edition_id,\$next_attempt))",'exact retry-attempt fingerprint scheduling guard missing');
$must($frest,"'/future/derive-text', array('methods'=>'POST','callback'=>array(__CLASS__,'derive_text'),'permission_callback'=>array(__CLASS__,'logged_in'))",'provider-derived mutating POST is no longer authenticated');
$must($reader,'encode_reading_dashboard_cursor','bounded reading-workspace continuation cursor missing');
$must($reader,"'Older reading progress'",'reading-workspace continuation control missing');
$must($main,"define('PLDR_DB_VERSION', '1.1.0')",'R24 unexpectedly drifted the DB schema version');
$must($main,"define('PLDR_CONTRACT_VERSION', '1.1.0')",'R24 unexpectedly drifted the integration contract version');
$doc=dirname(__DIR__).'/docs/TWENTY-ROUND-REVIEW-2026-08-13-R24.md';if(!is_file($doc)){fwrite(STDERR,"R24 review record missing.\n");exit(1);} $record=(string)file_get_contents($doc);for($i=1;$i<=20;$i++)$must($record,"## Round {$i}","R24 review record missing Round {$i}");
$must($record,'1.1.0-rc.3','R24 release identity evidence missing from the immutable R24 review record');
$must($record,'First-ten defect rounds: 1, 5, 7, 8, 9.','R24 first-ten defect accounting missing');
$must($record,'Final defect rounds: 1, 5, 7, 8, 9, 14, 15, 16, 17, 18, 19, 20.','R24 final defect accounting missing');
$must($record,'Final clean rounds: 2, 3, 4, 6, 10, 11, 12, 13.','R24 clean-round accounting missing');
echo "PLDR R24 fresh twenty-round corrective-review contract: PASS\n";
