<?php

defined('ABSPATH') || exit;

final class PLDR_Future_Shelves {
    public static function ensure_defaults(int $uid):void { global $wpdb;foreach(array('reading'=>'Reading now','later'=>'Read later','complete'=>'Completed','reference'=>'Important reference') as $type=>$name){$exists=$wpdb->get_var($wpdb->prepare('SELECT id FROM '.PLDR_Core::table('shelves').' WHERE user_id=%d AND shelf_type=%s LIMIT 1',$uid,$type));if(!$exists)$wpdb->insert(PLDR_Core::table('shelves'),array('shelf_key'=>PLDR_Core::uuid(),'user_id'=>$uid,'name'=>$name,'shelf_type'=>$type,'sort_order'=>0,'version'=>1,'created_at'=>PLDR_Core::now(),'updated_at'=>PLDR_Core::now()));} }
    public static function list():array { global $wpdb;$uid=get_current_user_id();if(!$uid)return array();self::ensure_defaults($uid);$rows=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.PLDR_Core::table('shelves').' WHERE user_id=%d ORDER BY sort_order ASC,id ASC',$uid),ARRAY_A)?:array();foreach($rows as &$row){$row['id']=(int)$row['id'];$row['count']=(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.PLDR_Core::table('shelf_items').' WHERE shelf_id=%d',$row['id']));}return $rows; }
    public static function create(string $name):array { global $wpdb;$uid=get_current_user_id();if(!$uid)return array('error'=>PLDR_Core::machine_error('pldr_shelf_login','Log in to create a private shelf.',401));$name=trim(sanitize_text_field($name));if(''===$name)return array('error'=>PLDR_Core::machine_error('pldr_shelf_name','Shelf name is required.',400));$key=PLDR_Core::uuid();$wpdb->insert(PLDR_Core::table('shelves'),array('shelf_key'=>$key,'user_id'=>$uid,'name'=>$name,'shelf_type'=>'custom','sort_order'=>0,'version'=>1,'created_at'=>PLDR_Core::now(),'updated_at'=>PLDR_Core::now()));return array('id'=>(int)$wpdb->insert_id,'shelf_key'=>$key,'name'=>$name); }
    public static function add(int $shelf_id,int $edition_id) { global $wpdb;$uid=get_current_user_id();if(!$uid)return PLDR_Core::machine_error('pldr_shelf_login','Log in to manage shelves.',401);$shelf=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.PLDR_Core::table('shelves').' WHERE id=%d AND user_id=%d',$shelf_id,$uid),ARRAY_A);if(!$shelf)return PLDR_Core::machine_error('pldr_shelf_missing','Shelf not found.',404);$edition=PLDR_Future_Data::require_edition($edition_id);if(is_wp_error($edition))return $edition;$wpdb->replace(PLDR_Core::table('shelf_items'),array('shelf_id'=>$shelf_id,'edition_id'=>$edition_id,'added_at'=>PLDR_Core::now()));return array('shelf_id'=>$shelf_id,'edition_id'=>$edition_id,'added'=>true); }
    public static function rename(int $shelf_id,string $name) { global $wpdb;$uid=get_current_user_id();if(!$uid)return PLDR_Core::machine_error('pldr_shelf_login','Log in to manage shelves.',401);$shelf=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.PLDR_Core::table('shelves').' WHERE id=%d AND user_id=%d',$shelf_id,$uid),ARRAY_A);if(!$shelf)return PLDR_Core::machine_error('pldr_shelf_missing','Shelf not found.',404);if('custom'!==$shelf['shelf_type'])return PLDR_Core::machine_error('pldr_shelf_system','Built-in Smart Shelves cannot be renamed.',409);$name=trim(sanitize_text_field($name));if(''===$name)return PLDR_Core::machine_error('pldr_shelf_name','Shelf name is required.',400);$wpdb->update(PLDR_Core::table('shelves'),array('name'=>$name,'version'=>(int)$shelf['version']+1,'updated_at'=>PLDR_Core::now()),array('id'=>$shelf_id,'user_id'=>$uid));return array('id'=>$shelf_id,'name'=>$name,'version'=>(int)$shelf['version']+1); }
    public static function remove(int $shelf_id) { global $wpdb;$uid=get_current_user_id();if(!$uid)return PLDR_Core::machine_error('pldr_shelf_login','Log in to manage shelves.',401);$shelf=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.PLDR_Core::table('shelves').' WHERE id=%d AND user_id=%d',$shelf_id,$uid),ARRAY_A);if(!$shelf)return PLDR_Core::machine_error('pldr_shelf_missing','Shelf not found.',404);if('custom'!==$shelf['shelf_type'])return PLDR_Core::machine_error('pldr_shelf_system','Built-in Smart Shelves cannot be deleted.',409);$wpdb->query('START TRANSACTION');$wpdb->delete(PLDR_Core::table('shelf_items'),array('shelf_id'=>$shelf_id));$deleted=$wpdb->delete(PLDR_Core::table('shelves'),array('id'=>$shelf_id,'user_id'=>$uid));if(false===$deleted){$wpdb->query('ROLLBACK');return PLDR_Core::machine_error('pldr_shelf_delete','Shelf could not be deleted.',500);}$wpdb->query('COMMIT');return array('id'=>$shelf_id,'deleted'=>true); }
    public static function remove_item(int $shelf_id,int $edition_id) { global $wpdb;$uid=get_current_user_id();if(!$uid)return PLDR_Core::machine_error('pldr_shelf_login','Log in to manage shelves.',401);$shelf=$wpdb->get_row($wpdb->prepare('SELECT id FROM '.PLDR_Core::table('shelves').' WHERE id=%d AND user_id=%d',$shelf_id,$uid),ARRAY_A);if(!$shelf)return PLDR_Core::machine_error('pldr_shelf_missing','Shelf not found.',404);$wpdb->delete(PLDR_Core::table('shelf_items'),array('shelf_id'=>$shelf_id,'edition_id'=>$edition_id));return array('shelf_id'=>$shelf_id,'edition_id'=>$edition_id,'removed'=>true); }
}
