<?php

defined('ABSPATH') || exit;

final class PLDR_Future_Preferences {
    public static function get(string $key='reader'):array { global $wpdb;$uid=get_current_user_id();if(!$uid)return array();$row=$wpdb->get_row($wpdb->prepare('SELECT preference_json,version,updated_at FROM '.PLDR_Core::table('future_prefs').' WHERE user_id=%d AND preference_key=%s',$uid,sanitize_key($key)),ARRAY_A);return $row?array('value'=>json_decode((string)$row['preference_json'],true)?:array(),'version'=>(int)$row['version'],'updated_at'=>$row['updated_at']):array('value'=>array(),'version'=>0); }
    public static function save(string $key,array $value,int $expected=0) { global $wpdb;$uid=get_current_user_id();if(!$uid)return PLDR_Core::machine_error('pldr_future_pref_login','Log in to synchronize advanced reading preferences.',401);$key=sanitize_key($key);$current=self::get($key);if($expected&&(int)$current['version']!==$expected)return PLDR_Core::machine_error('pldr_future_pref_conflict','Reading preferences changed on another device.',409,array('current_version'=>(int)$current['version']));$clean=self::sanitize($value);$version=max(1,(int)$current['version']+1);$now=PLDR_Core::now();if((int)$current['version']>0){$updated=$wpdb->query($wpdb->prepare('UPDATE '.PLDR_Core::table('future_prefs').' SET preference_json=%s,version=%d,updated_at=%s WHERE user_id=%d AND preference_key=%s AND version=%d',wp_json_encode($clean),$version,$now,$uid,$key,(int)$current['version']));if(1!==$updated)return PLDR_Core::machine_error('pldr_future_pref_conflict','Concurrent reading-preference update detected.',409);}else{$inserted=$wpdb->insert(PLDR_Core::table('future_prefs'),array('user_id'=>$uid,'preference_key'=>$key,'preference_json'=>wp_json_encode($clean),'version'=>$version,'updated_at'=>$now));if(false===$inserted)return PLDR_Core::machine_error('pldr_future_pref_store','Reading preferences could not be stored.',500);}return array('value'=>$clean,'version'=>$version,'updated_at'=>$now); }
    private static function sanitize(array $value):array { $allowed=array('layout','text_size','line_height','contrast','column_width','data_saver','tts_rate','tts_voice','language');$out=array();foreach($value as $k=>$v){$k=sanitize_key((string)$k);if(!in_array($k,$allowed,true))continue;$out[$k]=is_bool($v)?$v:(is_numeric($v)?(float)$v:sanitize_text_field((string)$v));}return $out; }
}
