<?php

defined('ABSPATH') || exit;

final class PLDR_Privacy {
    public static function hooks():void { add_filter('wp_privacy_personal_data_exporters',array(__CLASS__,'exporters'));add_filter('wp_privacy_personal_data_erasers',array(__CLASS__,'erasers')); }
    public static function exporters(array $exporters):array { $exporters['pldr-reading']=array('exporter_friendly_name'=>__('PDF Library private reading data','pdf-library-digital-reading'),'callback'=>array(__CLASS__,'export'));return $exporters; }
    public static function erasers(array $erasers):array { $erasers['pldr-reading']=array('eraser_friendly_name'=>__('PDF Library private reading data','pdf-library-digital-reading'),'callback'=>array(__CLASS__,'erase'));return $erasers; }
    private static function user_id(string $email):int { $user=get_user_by('email',$email);return $user?(int)$user->ID:0; }
    public static function export(string $email,int $page=1):array { global $wpdb;$user_id=self::user_id($email);if(!$user_id)return array('data'=>array(),'done'=>true);$limit=50;$offset=(max(1,$page)-1)*$limit;$data=array();$states=$wpdb->get_results($wpdb->prepare('SELECT s.*,d.public_id,d.title FROM '.PLDR_Core::table('reading_state').' s JOIN '.PLDR_Core::table('editions').' e ON e.id=s.edition_id JOIN '.PLDR_Core::table('documents').' d ON d.id=e.document_id WHERE s.user_id=%d ORDER BY s.updated_at DESC LIMIT %d OFFSET %d',$user_id,$limit,$offset),ARRAY_A);foreach($states as $row)$data[]=array('group_id'=>'pldr-reading-state','group_label'=>__('PDF Library reading progress','pdf-library-digital-reading'),'item_id'=>'progress-'.$row['edition_id'],'data'=>array(array('name'=>'Document','value'=>$row['title'].' ('.$row['public_id'].')'),array('name'=>'Last page','value'=>(int)$row['last_page']),array('name'=>'Percent','value'=>$row['percent']),array('name'=>'Updated','value'=>$row['updated_at'])));$items=$wpdb->get_results($wpdb->prepare('SELECT i.*,d.public_id,d.title FROM '.PLDR_Core::table('reading_items').' i JOIN '.PLDR_Core::table('editions').' e ON e.id=i.edition_id JOIN '.PLDR_Core::table('documents').' d ON d.id=e.document_id WHERE i.user_id=%d ORDER BY i.id ASC LIMIT %d OFFSET %d',$user_id,$limit,$offset),ARRAY_A);foreach($items as $row)$data[]=array('group_id'=>'pldr-reading-items','group_label'=>__('PDF Library bookmarks, highlights and private notes','pdf-library-digital-reading'),'item_id'=>'item-'.$row['id'],'data'=>array(array('name'=>'Document','value'=>$row['title'].' ('.$row['public_id'].')'),array('name'=>'Type','value'=>$row['item_type']),array('name'=>'Page','value'=>(int)$row['page_number']),array('name'=>'Anchor','value'=>$row['anchor_text']),array('name'=>'Private note','value'=>$row['note_text']),array('name'=>'Tags','value'=>$row['tags_json']),array('name'=>'Updated','value'=>$row['updated_at'])));$done=count($states)<$limit&&count($items)<$limit;return array('data'=>$data,'done'=>$done); }
    public static function erase(string $email,int $page=1):array { global $wpdb;$user_id=self::user_id($email);if(!$user_id)return array('items_removed'=>false,'items_retained'=>false,'messages'=>array(),'done'=>true);$hold=(bool)apply_filters('pldr_privacy_legal_hold',false,$user_id);if($hold)return array('items_removed'=>false,'items_retained'=>true,'messages'=>array(__('File 12 data is subject to a documented legal/rights hold and cannot yet be erased.','pdf-library-digital-reading')),'done'=>true);PLDR_Reading::clear($user_id);$wpdb->query($wpdb->prepare('UPDATE '.PLDR_Core::table('rights_cases').' SET reporter_id=0,updated_at=%s WHERE reporter_id=%d AND state=%s',PLDR_Core::now(),$user_id,'closed'));PLDR_Core::audit('privacy',0,'user_reading_erased',array('user_id'=>$user_id));return array('items_removed'=>true,'items_retained'=>false,'messages'=>array(__('Private reading progress, bookmarks, highlights and notes were erased. Closed rights cases were anonymized where no hold applied.','pdf-library-digital-reading')),'done'=>true); }
}
