from pathlib import Path


def replace(path, old, new):
    p=Path(path); s=p.read_text();
    if old not in s: raise SystemExit(f'marker missing: {path}: {old[:80]!r}')
    p.write_text(s.replace(old,new,1))

reader='pdf-library-foundation-12/includes/class-pldr-reader.php'
rest='pdf-library-foundation-12/includes/class-pldr-rest.php'

replace(reader,"        $scan_limit = (int) apply_filters('pldr_search_scan_limit', $suggested_limit, $args, $user_id);\n        $scan_limit = max($batch_size, min(20000, $scan_limit));","        $scan_limit_provider_failed = false;\n        try {\n            $scan_limit = (int) apply_filters('pldr_search_scan_limit', $suggested_limit, $args, $user_id);\n        } catch (Throwable $e) {\n            $scan_limit = $suggested_limit;\n            $scan_limit_provider_failed = true;\n            PLDR_Core::audit('search', 0, 'catalog_scan_limit_provider_failed', array('provider_failure'=>true), $user_id);\n        }\n        $scan_limit = max($batch_size, min(20000, $scan_limit));")
replace(reader,"            $rows = $wpdb->get_results($wpdb->prepare($sql, $params), ARRAY_A) ?: array();\n            if (!$rows) break;","            $wpdb->last_error = '';\n            $rows = $wpdb->get_results($wpdb->prepare($sql, $params), ARRAY_A);\n            if ('' !== (string) $wpdb->last_error) {\n                return array(\n                    'items'=>array(),'page'=>$page,'per_page'=>$per_page,'has_more'=>false,\n                    'error'=>PLDR_Core::machine_error('pldr_catalog_read','PDF Library catalog state could not be read reliably.',503,array('degraded'=>true)),\n                    'degraded'=>true,'scan_limit_provider_failed'=>$scan_limit_provider_failed,\n                );\n            }\n            $rows = is_array($rows) ? $rows : array();\n            if (!$rows) break;")
replace(reader,"            'raw_rows_scanned' => $raw_offset,\n        );","            'raw_rows_scanned' => $raw_offset,\n            'scan_limit_provider_failed' => $scan_limit_provider_failed,\n        );")
old="""    public static function ocr(int $edition_id, string $query, int $user_id = 0): array {
        global $wpdb;
        if (!PLDR_Access::can_access_edition($edition_id, 'read', $user_id)) return array();
        $needle = PLDR_Core::normalize_search($query);
        $needle_len=function_exists('mb_strlen')?mb_strlen($needle,'UTF-8'):strlen($needle); if ($needle_len < 2) return array();
        $variants = apply_filters('pldr_search_variants', array($needle), $needle, $edition_id);
        $variants = array_values(array_unique(array_filter(array_map('strval', (array) $variants))));
        $clauses = array(); $params = array();
        foreach (array_slice($variants, 0, 5) as $variant) { $clauses[] = 'normalized_text LIKE %s'; $params[] = '%' . $wpdb->esc_like(PLDR_Core::normalize_search($variant)) . '%'; }
        if (!$clauses) return array();
        array_unshift($params, $edition_id);
        $sql = 'SELECT page_number,language,quality_score,text_content FROM ' . PLDR_Core::table('ocr_text') . ' WHERE edition_id=%d AND (' . implode(' OR ', $clauses) . ') ORDER BY page_number ASC LIMIT 100';
        $rows = $wpdb->get_results($wpdb->prepare($sql, $params), ARRAY_A);
        return array_map(static function (array $row) use ($query): array {
            $text = (string) $row['text_content'];
            $pos = function_exists('mb_stripos') ? mb_stripos($text,$query,0,'UTF-8') : stripos($text,$query);
            $start = false === $pos ? 0 : max(0, $pos - 90);
            $snippet=function_exists('mb_substr')?mb_substr($text,$start,240,'UTF-8'):substr($text,$start,240);
            return array('page' => (int) $row['page_number'], 'language' => $row['language'], 'quality' => (float) $row['quality_score'], 'snippet' => $snippet);
        }, $rows ?: array());
    }
"""
new="""    public static function ocr(int $edition_id, string $query, int $user_id = 0): array {
        global $wpdb;
        if (!PLDR_Access::can_access_edition($edition_id, 'read', $user_id)) return array('error'=>PLDR_Core::machine_error('pldr_ocr_forbidden','Document text search is unavailable.',404));
        $needle = PLDR_Core::normalize_search($query);
        $needle_len=function_exists('mb_strlen')?mb_strlen($needle,'UTF-8'):strlen($needle);
        if ($needle_len < 2) return array('error'=>PLDR_Core::machine_error('pldr_ocr_query_short','Document text search requires at least two characters.',400));
        if ($needle_len > 160) return array('error'=>PLDR_Core::machine_error('pldr_ocr_query_long','Document text search query is too long.',400,array('max_characters'=>160)));
        try {
            $variants = apply_filters('pldr_search_variants', array($needle), $needle, $edition_id);
        } catch (Throwable $e) {
            PLDR_Core::audit('edition',$edition_id,'ocr_search_variant_provider_failed',array('provider_failure'=>true),$user_id);
            return array('error'=>PLDR_Core::machine_error('pldr_ocr_variant_provider','Document text-search expansion is temporarily unavailable.',503,array('degraded'=>true,'provider_failure'=>true)));
        }
        $variants = array_values(array_unique(array_filter(array_map(static function($value):string {
            $value=PLDR_Core::normalize_search((string)$value);
            return function_exists('mb_substr')?mb_substr($value,0,160,'UTF-8'):substr($value,0,160);
        }, (array) $variants))));
        $clauses = array(); $params = array();
        foreach (array_slice($variants, 0, 5) as $variant) { if(''===$variant)continue; $clauses[] = 'normalized_text LIKE %s'; $params[] = '%' . $wpdb->esc_like($variant) . '%'; }
        if (!$clauses) return array('error'=>PLDR_Core::machine_error('pldr_ocr_variants','No safe document text-search variant was available.',400));
        array_unshift($params, $edition_id);
        $sql = 'SELECT page_number,language,quality_score,text_content FROM ' . PLDR_Core::table('ocr_text') . ' WHERE edition_id=%d AND (' . implode(' OR ', $clauses) . ') ORDER BY page_number ASC LIMIT 100';
        $wpdb->last_error='';
        $rows = $wpdb->get_results($wpdb->prepare($sql, $params), ARRAY_A);
        if(''!==(string)$wpdb->last_error)return array('error'=>PLDR_Core::machine_error('pldr_ocr_read','Document OCR search state could not be read reliably.',503,array('degraded'=>true)));
        return array_map(static function (array $row) use ($query): array {
            $text = (string) $row['text_content'];
            $pos = function_exists('mb_stripos') ? mb_stripos($text,$query,0,'UTF-8') : stripos($text,$query);
            $start = false === $pos ? 0 : max(0, $pos - 90);
            $snippet=function_exists('mb_substr')?mb_substr($text,$start,240,'UTF-8'):substr($text,$start,240);
            return array('page' => (int) $row['page_number'], 'language' => $row['language'], 'quality' => (float) $row['quality_score'], 'snippet' => $snippet);
        }, is_array($rows)?$rows:array());
    }
"""
replace(reader,old,new)
replace(reader,"        $row = $wpdb->get_row($wpdb->prepare('SELECT * FROM ' . PLDR_Core::table('reading_state') . ' WHERE user_id=%d AND edition_id=%d', $user_id, $edition_id), ARRAY_A);\n        return $row ? array('page' => (int) $row['last_page'], 'percent' => (float) $row['percent'], 'updated_at' => $row['updated_at']) : array('page' => 1, 'percent' => 0);","        $wpdb->last_error='';\n        $row = $wpdb->get_row($wpdb->prepare('SELECT * FROM ' . PLDR_Core::table('reading_state') . ' WHERE user_id=%d AND edition_id=%d', $user_id, $edition_id), ARRAY_A);\n        if(''!==(string)$wpdb->last_error)return array('page'=>1,'percent'=>0,'error'=>PLDR_Core::machine_error('pldr_progress_read','Private reading progress could not be read reliably.',503,array('degraded'=>true)));\n        return $row ? array('page' => (int) $row['last_page'], 'percent' => (float) $row['percent'], 'updated_at' => $row['updated_at']) : array('page' => 1, 'percent' => 0);")
replace(reader,"        $note = sanitize_textarea_field((string) ($data['note'] ?? ''));\n        if ('note' === $type && '' === trim($note)) return PLDR_Core::machine_error('pldr_note_empty', 'A private note cannot be empty.', 400);\n        $ok = $wpdb->insert(PLDR_Core::table('reading_items'), array('user_id' => $user_id, 'edition_id' => $edition_id, 'item_type' => $type, 'page_number' => $page, 'anchor_text' => sanitize_text_field((string) ($data['anchor'] ?? '')), 'note_text' => $note, 'tags_json' => wp_json_encode(PLDR_Core::sanitize_json_list($data['tags'] ?? array())), 'version' => 1, 'created_at' => PLDR_Core::now(), 'updated_at' => PLDR_Core::now()));","        $note = self::limit_text(sanitize_textarea_field((string) ($data['note'] ?? '')),4000);\n        if ('note' === $type && '' === trim($note)) return PLDR_Core::machine_error('pldr_note_empty', 'A private note cannot be empty.', 400);\n        $anchor=self::limit_text(sanitize_text_field((string)($data['anchor']??'')),500);\n        $tags=array_slice(PLDR_Core::sanitize_json_list($data['tags']??array()),0,30);\n        $tags=array_map(static fn(string $tag):string=>self::limit_text($tag,80),$tags);\n        $tags_json=wp_json_encode($tags);\n        if(!is_string($tags_json))return PLDR_Core::machine_error('pldr_item_tags','Private reading-item tags could not be encoded safely.',400);\n        $ok = $wpdb->insert(PLDR_Core::table('reading_items'), array('user_id' => $user_id, 'edition_id' => $edition_id, 'item_type' => $type, 'page_number' => $page, 'anchor_text' => $anchor, 'note_text' => $note, 'tags_json' => $tags_json, 'version' => 1, 'created_at' => PLDR_Core::now(), 'updated_at' => PLDR_Core::now()));")
replace(reader,"        $rows = $wpdb->get_results($wpdb->prepare('SELECT id,item_type,page_number,anchor_text,note_text,tags_json,version,created_at,updated_at FROM ' . PLDR_Core::table('reading_items') . ' WHERE user_id=%d AND edition_id=%d ORDER BY page_number ASC,id ASC', $user_id, $edition_id), ARRAY_A);\n        foreach ($rows as &$row) {","        $wpdb->last_error='';\n        $rows = $wpdb->get_results($wpdb->prepare('SELECT id,item_type,page_number,anchor_text,note_text,tags_json,version,created_at,updated_at FROM ' . PLDR_Core::table('reading_items') . ' WHERE user_id=%d AND edition_id=%d ORDER BY page_number ASC,id ASC LIMIT 1000', $user_id, $edition_id), ARRAY_A);\n        if(''!==(string)$wpdb->last_error)return array('error'=>PLDR_Core::machine_error('pldr_items_read','Private reading items could not be read reliably.',503,array('degraded'=>true)));\n        $rows=is_array($rows)?$rows:array();\n        foreach ($rows as &$row) {")
replace(reader,"        return $rows ?: array();\n    }\n\n    public static function delete_item","        return $rows ?: array();\n    }\n\n    private static function limit_text(string $value,int $length):string {\n        return function_exists('mb_substr')?mb_substr($value,0,$length,'UTF-8'):substr($value,0,$length);\n    }\n\n    public static function delete_item")
replace(reader,"        $result = PLDR_Search::search(array_merge($_GET, $args), get_current_user_id());\n        ob_start();","        $result = PLDR_Search::search(array_merge($_GET, $args), get_current_user_id());\n        if(isset($result['error'])&&is_wp_error($result['error']))return self::state_html('error');\n        ob_start();")
replace(reader,"        $state = PLDR_Reading::state((int)$edition['id']);\n        $config=array","        $state = PLDR_Reading::state((int)$edition['id']);\n        if(isset($state['error'])&&is_wp_error($state['error']))return self::state_html('error');\n        try{$interaction_html=(string)apply_filters('pldr_interaction_controls_html','',(int)$edition['id'],PLDR_Core::public_document_dto($doc,$edition));}\n        catch(Throwable $e){$interaction_html='';PLDR_Core::audit('edition',(int)$edition['id'],'reader_interaction_provider_failed',array('provider_failure'=>true));}\n        $config=array")
replace(reader,"<section class=\"pldr-reader-tools\"><?php echo wp_kses_post((string)apply_filters('pldr_interaction_controls_html','',(int)$edition['id'],PLDR_Core::public_document_dto($doc,$edition))); ?>","<section class=\"pldr-reader-tools\"><?php echo wp_kses_post($interaction_html); ?>")
replace(reader,"        $rows=$wpdb->get_results($wpdb->prepare('SELECT s.*,e.document_id,d.public_id,d.title,d.slug FROM '.PLDR_Core::table('reading_state').' s JOIN '.PLDR_Core::table('editions').' e ON e.id=s.edition_id JOIN '.PLDR_Core::table('documents').' d ON d.id=e.document_id WHERE s.user_id=%d ORDER BY s.updated_at DESC LIMIT 100',$uid),ARRAY_A)?:array();","        $wpdb->last_error='';\n        $rows=$wpdb->get_results($wpdb->prepare('SELECT s.*,e.document_id,d.public_id,d.title,d.slug FROM '.PLDR_Core::table('reading_state').' s JOIN '.PLDR_Core::table('editions').' e ON e.id=s.edition_id JOIN '.PLDR_Core::table('documents').' d ON d.id=e.document_id WHERE s.user_id=%d ORDER BY s.updated_at DESC LIMIT 100',$uid),ARRAY_A);\n        if(''!==(string)$wpdb->last_error)return self::state_html('error');\n        $rows=is_array($rows)?$rows:array();")
replace(reader,"    private static function cover_token(int $edition_id): string { global $wpdb; $oid=(int)$wpdb->get_var($wpdb->prepare('SELECT object_id FROM '.PLDR_Core::table('derivatives').' WHERE edition_id=%d AND derivative_type=%s AND status=%s LIMIT 1',$edition_id,'cover','available')); if(!$oid)return'';","    private static function cover_token(int $edition_id): string { global $wpdb; $wpdb->last_error=''; $oid=(int)$wpdb->get_var($wpdb->prepare('SELECT object_id FROM '.PLDR_Core::table('derivatives').' WHERE edition_id=%d AND derivative_type=%s AND status=%s LIMIT 1',$edition_id,'cover','available')); if(''!==(string)$wpdb->last_error){PLDR_Core::audit('edition',$edition_id,'cover_derivative_read_failed',array());return'';} if(!$oid)return'';")
replace(reader,"    private static function thumbnail_tokens(int $edition_id): array { global $wpdb; $rows=$wpdb->get_results($wpdb->prepare('SELECT page_number,object_id FROM '.PLDR_Core::table('derivatives').' WHERE edition_id=%d AND derivative_type=%s AND status=%s ORDER BY page_number ASC LIMIT %d',$edition_id,'thumbnail','available',self::THUMBNAIL_PREVIEW_LIMIT),ARRAY_A); $out=array();","    private static function thumbnail_tokens(int $edition_id): array { global $wpdb; $wpdb->last_error=''; $rows=$wpdb->get_results($wpdb->prepare('SELECT page_number,object_id FROM '.PLDR_Core::table('derivatives').' WHERE edition_id=%d AND derivative_type=%s AND status=%s ORDER BY page_number ASC LIMIT %d',$edition_id,'thumbnail','available',self::THUMBNAIL_PREVIEW_LIMIT),ARRAY_A); if(''!==(string)$wpdb->last_error){PLDR_Core::audit('edition',$edition_id,'thumbnail_derivative_read_failed',array());return array();} $rows=is_array($rows)?$rows:array(); $out=array();")

replace(rest,"    public static function library(WP_REST_Request $request) { return rest_ensure_response(PLDR_Search::search($request->get_params(),get_current_user_id())); }","    public static function library(WP_REST_Request $request) { $result=PLDR_Search::search($request->get_params(),get_current_user_id());if(isset($result['error'])&&is_wp_error($result['error']))return $result['error'];return rest_ensure_response($result); }")
replace(rest,"        $thumb_table=PLDR_Core::table('derivatives');\n        $thumb_total=(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.$thumb_table.' WHERE edition_id=%d AND derivative_type=%s AND status=%s',$edition_id,'thumbnail','available'));\n        $thumb_rows=$wpdb->get_results($wpdb->prepare('SELECT page_number,object_id FROM '.$thumb_table.' WHERE edition_id=%d AND derivative_type=%s AND status=%s ORDER BY page_number ASC LIMIT %d',$edition_id,'thumbnail','available',self::READER_THUMB_LIMIT),ARRAY_A)?:array();","        $thumb_table=PLDR_Core::table('derivatives');\n        $wpdb->last_error='';\n        $thumb_total=(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.$thumb_table.' WHERE edition_id=%d AND derivative_type=%s AND status=%s',$edition_id,'thumbnail','available'));\n        if(''!==(string)$wpdb->last_error)return PLDR_Core::machine_error('pldr_reader_thumbnail_count','Reader thumbnail state could not be counted reliably.',503,array('degraded'=>true));\n        $wpdb->last_error='';\n        $thumb_rows=$wpdb->get_results($wpdb->prepare('SELECT page_number,object_id FROM '.$thumb_table.' WHERE edition_id=%d AND derivative_type=%s AND status=%s ORDER BY page_number ASC LIMIT %d',$edition_id,'thumbnail','available',self::READER_THUMB_LIMIT),ARRAY_A);\n        if(''!==(string)$wpdb->last_error)return PLDR_Core::machine_error('pldr_reader_thumbnail_read','Reader thumbnail state could not be read reliably.',503,array('degraded'=>true));\n        $thumb_rows=is_array($thumb_rows)?$thumb_rows:array();")
replace(rest,"        $policy=PLDR_Core::policy((int)$edition['document_id']);\n        return rest_ensure_response(array(","        $wpdb->last_error='';\n        $policy=PLDR_Core::policy((int)$edition['document_id']);\n        if(''!==(string)$wpdb->last_error)return PLDR_Core::machine_error('pldr_reader_policy_read','Reader access-policy state could not be read reliably.',503,array('degraded'=>true));\n        if(!$policy)return PLDR_Core::machine_error('pldr_reader_policy_missing','Reader access policy is unavailable.',503,array('degraded'=>true));\n        $reading=PLDR_Reading::state($edition_id);\n        if(isset($reading['error'])&&is_wp_error($reading['error']))return $reading['error'];\n        $accessibility=self::accessibility_metadata($edition_id,$edition);\n        if(isset($accessibility['error'])&&is_wp_error($accessibility['error']))return $accessibility['error'];\n        return rest_ensure_response(array(")
replace(rest,"            'reading'=>PLDR_Reading::state($edition_id),","            'reading'=>$reading,")
replace(rest,"            'accessibility'=>self::accessibility_metadata($edition_id,$edition),","            'accessibility'=>$accessibility,")
old="    private static function accessibility_metadata(int $edition_id,array $edition):array { global $wpdb;$ocr=$wpdb->get_row($wpdb->prepare('SELECT status,quality_score,language FROM '.PLDR_Core::table('derivatives').' WHERE edition_id=%d AND derivative_type=%s LIMIT 1',$edition_id,'ocr-status'),ARRAY_A);$thumbs=(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.PLDR_Core::table('derivatives').' WHERE edition_id=%d AND derivative_type=%s AND status=%s',$edition_id,'thumbnail','available'));return array('title'=>$edition['title'],'author'=>$edition['author_name'],'language'=>$edition['language'],'pages'=>(int)$edition['pages'],'ocr_status'=>$ocr['status']??'unknown','ocr_quality'=>isset($ocr['quality_score'])?(float)$ocr['quality_score']:0,'ocr_language'=>$ocr['language']??$edition['language'],'thumbnail_pages'=>$thumbs,'screen_reader_fallback'=>$ocr&&'available'===$ocr['status']?'ocr-text':'document-metadata'); }"
new="""    private static function accessibility_metadata(int $edition_id,array $edition):array {
        global $wpdb;
        $wpdb->last_error='';
        $ocr=$wpdb->get_row($wpdb->prepare('SELECT status,quality_score,language FROM '.PLDR_Core::table('derivatives').' WHERE edition_id=%d AND derivative_type=%s LIMIT 1',$edition_id,'ocr-status'),ARRAY_A);
        if(''!==(string)$wpdb->last_error)return array('error'=>PLDR_Core::machine_error('pldr_reader_a11y_ocr_read','Reader accessibility OCR state could not be read reliably.',503,array('degraded'=>true)));
        $wpdb->last_error='';
        $thumbs=(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.PLDR_Core::table('derivatives').' WHERE edition_id=%d AND derivative_type=%s AND status=%s',$edition_id,'thumbnail','available'));
        if(''!==(string)$wpdb->last_error)return array('error'=>PLDR_Core::machine_error('pldr_reader_a11y_thumbnail_read','Reader accessibility preview state could not be read reliably.',503,array('degraded'=>true)));
        return array('title'=>$edition['title'],'author'=>$edition['author_name'],'language'=>$edition['language'],'pages'=>(int)$edition['pages'],'ocr_status'=>$ocr['status']??'unknown','ocr_quality'=>isset($ocr['quality_score'])?(float)$ocr['quality_score']:0,'ocr_language'=>$ocr['language']??$edition['language'],'thumbnail_pages'=>$thumbs,'screen_reader_fallback'=>$ocr&&'available'===$ocr['status']?'ocr-text':'document-metadata');
    }"""
replace(rest,old,new)
replace(rest,"    public static function ocr_search(WP_REST_Request $request) { return rest_ensure_response(array('items'=>PLDR_Search::ocr(absint($request['edition']),(string)$request['q'],get_current_user_id()))); }","    public static function ocr_search(WP_REST_Request $request) { $result=PLDR_Search::ocr(absint($request['edition']),(string)$request['q'],get_current_user_id());if(isset($result['error'])&&is_wp_error($result['error']))return $result['error'];return rest_ensure_response(array('items'=>$result)); }")
replace(rest,"        $rows=$wpdb->get_results($wpdb->prepare('SELECT id,item_type,page_number,anchor_text,note_text,tags_json,version,created_at,updated_at FROM '.$table.' WHERE user_id=%d AND edition_id=%d ORDER BY page_number ASC,id ASC LIMIT %d OFFSET %d',$uid,$edition_id,$limit+1,$offset),ARRAY_A)?:array();","        $wpdb->last_error='';\n        $rows=$wpdb->get_results($wpdb->prepare('SELECT id,item_type,page_number,anchor_text,note_text,tags_json,version,created_at,updated_at FROM '.$table.' WHERE user_id=%d AND edition_id=%d ORDER BY page_number ASC,id ASC LIMIT %d OFFSET %d',$uid,$edition_id,$limit+1,$offset),ARRAY_A);\n        if(''!==(string)$wpdb->last_error)return PLDR_Core::machine_error('pldr_items_read','Private reading items could not be read reliably.',503,array('degraded'=>true));\n        $rows=is_array($rows)?$rows:array();")
replace(rest,"        $row=$wpdb->get_row($wpdb->prepare('SELECT id FROM '.PLDR_Core::table('reading_items').' WHERE id=%d AND user_id=%d',$item_id,$user_id),ARRAY_A);\n        if(!$row)return PLDR_Core::machine_error('pldr_item_missing','Private reading item was not found.',404);","        $wpdb->last_error='';\n        $row=$wpdb->get_row($wpdb->prepare('SELECT id FROM '.PLDR_Core::table('reading_items').' WHERE id=%d AND user_id=%d',$item_id,$user_id),ARRAY_A);\n        if(''!==(string)$wpdb->last_error)return PLDR_Core::machine_error('pldr_item_read','Private reading-item state could not be read reliably.',503,array('degraded'=>true));\n        if(!$row)return PLDR_Core::machine_error('pldr_item_missing','Private reading item was not found.',404);")
