<?php
defined('ABSPATH')||exit;
final class SPL_Helpers{
 const TYPE='spl_document';const TAX='spl_category';const DOCTYPE='spl_document_type';
 public static function types(){return array('book'=>'Book','reference-book'=>'Reference Book','research-paper'=>'Research Paper','clinical-study'=>'Clinical Study','educational-notes'=>'Educational Notes','lecture-handout'=>'Lecture Handout','materia-medica'=>'Materia Medica','repertory'=>'Repertory','philosophy'=>'Philosophy','anatomy'=>'Anatomy','pathology'=>'Pathology','nutrition'=>'Nutrition','public-health'=>'Public Health','principles-hygiene'=>'Principles of Hygiene','islamic-spiritual-healing'=>'Islamic Spiritual Healing','historical-document'=>'Historical Document');}
 public static function categories(){return array('classical-homeopathy'=>'Classical Homeopathy','homeopathy-education'=>'Homeopathy Education','materia-medica'=>'Materia Medica','repertory'=>'Repertory','clinical-education'=>'Clinical Education','patient-cases'=>'Patient Cases','homeopathy-philosophy'=>'Homeopathy Philosophy','research'=>'Research','nutrition'=>'Nutrition','public-health-education'=>'Public Health Education','pathology'=>'Pathology','anatomy'=>'Anatomy','principles-hygiene'=>'Principles of Hygiene','islamic-spiritual-healing'=>'Islamic Spiritual Healing','platform-publications'=>'Platform Publications','historical-homeopathy'=>'Historical Homeopathy');}
 public static function founder($id=0){$id=$id?:get_current_user_id();return$id&&$id===absint(get_option('spf_founder_user_id',0));}public static function doctor($id=0){$id=$id?:get_current_user_id();return$id&&class_exists('SPD_Helpers')&&SPD_Helpers::is_doctor($id)&&'verified'===SPD_Helpers::verification_status($id);}public static function can_submit($id=0){$id=$id?:get_current_user_id();return$id&&(user_can($id,'manage_pdf_library')||self::founder($id)||self::doctor($id));}public static function status(){return current_user_can('manage_pdf_library')||self::founder()?'publish':'pending';}
 public static function meta($id,$key,$default=''){$v=get_post_meta(absint($id),'_spl_'.$key,true);return''===$v?$default:$v;}public static function term($id,$tax){$t=get_the_terms($id,$tax);return$t&&!is_wp_error($t)?$t[0]->name:'';}
 public static function storage(){$u=wp_upload_dir();$d=trailingslashit($u['basedir']).'spl-secure';if(!is_dir($d)){wp_mkdir_p($d);file_put_contents($d.'/index.php','<?php http_response_code(403); exit;');file_put_contents($d.'/.htaccess','Deny from all');file_put_contents($d.'/web.config','<configuration><system.webServer><authorization><deny users="*" /></authorization></system.webServer></configuration>');}return$d;}private static function key(){return hash('sha256',wp_salt('auth').'|spl-pdf',true);}public static function encrypt($b){$iv=random_bytes(12);$tag='';$c=openssl_encrypt($b,'aes-256-gcm',self::key(),OPENSSL_RAW_DATA,$iv,$tag);return false===$c?false:'SPL1'.$iv.$tag.$c;}public static function decrypt($b){if(0!==strpos($b,'SPL1'))return false;return openssl_decrypt(substr($b,32),'aes-256-gcm',self::key(),OPENSSL_RAW_DATA,substr($b,4,12),substr($b,16,16));}
 public static function stream_url($id,$download=false){return wp_nonce_url(admin_url('admin-post.php?action=spl_stream&document_id='.absint($id).'&download='.($download?1:0)),'spl_stream_'.absint($id));}public static function nav(){return class_exists('SDD_Helpers')?str_replace('class="sdd-main-nav"','class="spl-main-nav"',SDD_Helpers::navigation()):'';}
}
